### ISSUE TITLE
Failed to load schema from ./server/graphql/schema.graphql

### ISSUE THREAD

**Issue by deadcoder0904** [graphql-nexus/nexus-prisma#156]
I am unable to create `schema.graphql` file when using `prisma` + [nexus-prisma](https://github.com/prisma/nexus-prisma) & thus unable to generate GraphQL Codegen (i tried this on my working setup that deleting `schema.graphql` throws the same error)

It throws the following error:

> Failed to load schema from ./server/graphql/schema.graphql:

My `codegen.yml` looks like:

```yml
schema: ./server/graphql/schema.graphql
documents:
  - '**/*.graphql'
  - '!/server/graphql/schema.graphql'
generates:
  /client/graphql/types.generated.ts:
    plugins:
      - typescript
  ./:
    preset: near-operation-file
    presetConfig:
      baseTypesPath: /client/graphql/types.generated.ts
    plugins:
      - typescript-operations
      - typescript-urql
```

And my `server/graphql/schema.ts` looks like:

```ts
import { makeSchema } from 'nexus'
import path from 'path'

import User from './User'

const shouldGenerateArtifacts =
  process.env.NODE_ENV === 'development' || !!process.env.GENERATE

export const schema = makeSchema({
  types: [User],
  plugins: [],
  // Type the GraphQL context when used in Nexus resolvers
  contextType: {
    module: path.join(process.cwd(), 'pages/api/index.ts'),
    export: 'GraphQLContext',
  },
  // Generate the files
  shouldGenerateArtifacts,
  outputs: {
    typegen: path.join(
      process.cwd(),
      'server/graphql/nexus-types.generated.ts'
    ),
    schema: path.join(process.cwd(), 'server/graphql/schema.graphql'),
  },
})
```

How do I make sure it creates `server/graphql/schema.graphql` before graphql-codegen runs?

Repro is available on `prisma` branch on this commit → https://github.com/deadcoder0904/twitter-api-v2-3-legged-login-using-next-connect/commit/60d7924e76b59550fed80d76ce5662325a1b7b0e

See the latest commits to find it working with vanilla `nexus` so I presume it's `nexus-prisma` error.
